package main.rice.node;

import main.rice.obj.APyObj;
import main.rice.obj.PyListObj;
import java.util.*;

// public class PyListNode<InnerType extends ____________> extends /either Aiterable or APy {
public class PyListNode<InnerType extends APyObj> extends AIterablePyNode<PyListObj<InnerType>, InnerType> {

     /**
     //     * The domain for exhaustive generation.
     //     */
    protected List<Number> exDomain;

    /**
     * The domain for random generation.
     */
    protected List<Number> ranDomain;

    /**
     * The RNG used for random generation.
     */
    protected Random rand = new Random();


    /**
     * PyListNode constructor. Will create a PyListNode encapsulating an innerNode.
     * @param innerNode : innerNode of type APyNode to be placed in PyListNode
     */
    public PyListNode(APyNode<InnerType> innerNode) {
        this.leftChild = innerNode;
    }



    /**
     * Generates all valid PyListObjs of type InnerType within the exhaustive domain.
     *
     * @return a set of PyListObjs of type InnerType comprising the exhaustive domain
     */
    public Set<PyListObj<InnerType>> genExVals() {
        // PRE PROCESS
        Set<PyListObj<InnerType>> retLi = new HashSet<>();
        List<Number> exDomainCopy = this.getExDomain();
        List<Integer> exDomainInts = new ArrayList<>();
        for (Number len : exDomainCopy) {
            int temp = (int) len;
            exDomainInts.add(temp);
        }
        Collections.sort(exDomainInts);

        int lenSize = this.getExDomain().size();
        int maxVal = exDomainInts.get(lenSize - 1);

        // RECURSION
        Set<InnerType> childGenExVals = this.getLeftChild().genExVals();
        Set<List<InnerType>> helper = genExValsRecHelper(maxVal, childGenExVals);

        // POST PROCESSING
        for (List<InnerType> li : helper) {
            // remove sets of length not in the given domain
            if (this.getExDomain().contains(li.size())) {
                PyListObj liNode = new PyListObj(li);
                retLi.add(liNode);
            }
        }
        return retLi;

    }


    /**
     * Generate a random PyListObj containing random InnerTypes (generated by their
     *          own genRandVal()) and is of a randomly selected length from the random domain
     *
     * @return : a PyListObj of a random length randomly chosen from the random domain
     *              with values of type InnerType that were randomly generated from
     *              InnerType's domain
     */
    public PyListObj<InnerType> genRandVal() {
        // create list of inner type
        List<InnerType> listInner = new ArrayList<>();

        // get length randomly from random domain
        int len = (int) this.ranDomainChoice();

        // randomly select length from domain
        for (int i = 0; i < len; i++) {
            listInner.add(this.getLeftChild().genRandVal());
        }

        // post processing
        // create PyListObj
        PyListObj<InnerType> randList = new PyListObj<>(listInner);

        return randList;
    }
}


